# Generated by Django 4.2.7 on 2025-10-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, help_text='Téléchargez votre CV au format PDF', null=True, upload_to='cv/'),
        ),
    ]
