# Generated by Django 4.2.7 on 2025-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Image de profil', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(blank=True, help_text="Logo de l'institution", null=True, upload_to='institutions/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='companies/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du projet', null=True, upload_to='projects/'),
        ),
    ]
