# Generated by Django 4.2.7 on 2025-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_about_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url_2',
            field=models.URLField(blank=True),
        ),
    ]
