# Generated by Django 4.2.7 on 2025-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_github_url_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Image du certificat', null=True, upload_to='certificates/')),
                ('credential_url', models.URLField(blank=True, help_text='Lien vers le certificat (optionnel)')),
                ('verified', models.BooleanField(default=False, help_text='Indique si le certificat est vérifié')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-order', '-issued_date'],
            },
        ),
    ]
