# Generated by Django 4.2.7 on 2025-10-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='Fichier du certificat (PDF, etc.)', null=True, upload_to='certificates/files/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Image/thumbnail du certificat (optionnel)', null=True, upload_to='certificates/'),
        ),
    ]
