# Generated by Django 4.2.7 on 2025-10-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificate_file_alter_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_count', models.IntegerField(default=15, help_text='Nombre de projets réalisés')),
                ('years_experience', models.IntegerField(default=3, help_text="Années d'expérience")),
                ('technologies_count', models.IntegerField(default=25, help_text='Nombre de technologies maîtrisées')),
                ('satisfaction_rate', models.IntegerField(default=100, help_text='Taux de satisfaction en %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistiques',
                'verbose_name_plural': 'Statistiques',
            },
        ),
    ]
