# Generated by Django 4.2.7 on 2025-10-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tawk_to_widget_id', models.CharField(blank=True, help_text='ID du widget Tawk.to (ex: 5f8a9b1c2d3e4f5g6h7i8j9k/default)', max_length=255)),
                ('enable_chat', models.BooleanField(default=True, help_text='Activer/Désactiver le chat en direct')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres du Site',
            },
        ),
    ]
