# Generated by Django 4.2.7 on 2025-10-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.URLField(blank=True, help_text='URL de la vidéo de démonstration (YouTube, Vimeo, ou lien direct vers .mp4)'),
        ),
    ]
