# Generated by Django 4.2.7 on 2025-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_demo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_video',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_file',
            field=models.FileField(blank=True, help_text='Ou uploadez une vidéo locale (.mp4, .webm, .mov)', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='URL de la vidéo (YouTube, Vimeo, ou lien direct)'),
        ),
    ]
